---
- name: Install Apache web server
  hosts: [webserver1 webserver2]
  become: yes
  become_method: sudo
  gather_facts: true
  tags: [web]

  tasks:
    - name: Update the software package repository
      apk:
        update_cache: yes 
    - name: Install Apache
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - apache2
        
    - wait_for:
        port: 80
        delay: 90
